{
 "title": "Direct Monitoring",
 "time": { "from": "now-6M", "to": "now" },
 "panels": [
  {
   "title": "SCORE ALSFRS-R",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| project \"id\", \"score\"=\"alsfrs_r.value\"",
     "url": "http://ngsi-api:3000/entities?type=HealthRawInformation&id=urn%3Angsi-ld%3AHealthRawInformation%3Apatient2&limit=100&offset=0",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Blood Oxygenation (spO2)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_index AS \"time\",\n  spo2 AS \"SpO2\"\nFROM doc.ethealthrawinformation\nWHERE $__timeFilter(time_index)\nORDER BY time_index ASC"
    }
   ]
  },
  {
   "title": "Heart Rate (bpm)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_index AS \"time\",\n  hr AS \"Heart Rate\"\nFROM doc.ethealthrawinformation\nWHERE $__timeFilter(time_index)\nORDER BY time_index ASC"
    }
   ]
  },
  {
   "title": "Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_index AS \"time\",\n  activity AS \"activity\"\nFROM doc.ethealthrawinformation\nWHERE $__timeFilter(time_index)\nORDER BY time_index ASC"
    }
   ]
  }
 ]
}